DOANWEB/DOANWEB/Controllers/LAPTOPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEB.Controllers
{
    public class LAPTOPController : Controller
    {
        //
        // GET: /LAPTOP/
        MUABANLAPTOPDataContext db = new MUABANLAPTOPDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LAPPartial()
        {
            var ListSP = db.SANPHAMs.OrderBy(cd => cd.GIABAN).ToList();

            return View(ListSP);
        }
        public ActionResult XemChiTiet(string ms)
        {
            SANPHAM SP = db.SANPHAMs.Single(s => s.MASP == ms);
            if (SP == null)
            {
                return HttpNotFound();
            }
            return View(SP);
        }
        public ActionResult KhuyenMai()
        {
            var ListKM = db.KHUYENMAIs.OrderBy(cd => cd.MATIN).ToList();

            return View(ListKM);
        }
    }
}

DOANWEB/DOANWEB/Controllers/NSXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEB.Controllers
{
    public class NSXController : Controller
    {
        //
        // GET: /NSX/
        MUABANLAPTOPDataContext db = new MUABANLAPTOPDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult NSXPartial()
        {
            var ListNSX = db.NSXes.Take(10).OrderBy(cd => cd.TENNSX).ToList();

            return View(ListNSX);
        }
        public ActionResult LAPTOPTHEONSX(string MaNSX)
        {
            var ListLAP = db.SANPHAMs.Where(s => s.MANSX == MaNSX).OrderBy(s => s.GIABAN).ToList();
            if (ListLAP.Count == 0)
            {
                ViewBag.LAP = "Không có laptop nào thuộc hãng  sản xuất này !";
            }
            return View(ListLAP);
        }
    }
}

DOANWEB/DOANWEB/Views/NSX/LAPTOPTHEONSX.cshtml
@{
    ViewBag.Title = "LAPTOPTHEONSX";
    Layout = "~/Views/SHARE/USERLAYOUT.cshtml";
}

<h2>LAPTOP THEO HÃNG SẢN XUẤT</h2>
@ViewBag.LAP
<div class="row">
    @{
        foreach (var item in Model)
        {
        <div class="col-4">
            <img src="@Url.Content("~/HinhAnhSP/"+item.HINHANH)" width="70%" height="70%" alt="Image" />
            @if (item.TENSP.Length > 30)
            {
                <p><strong title="@item.TENSP">Laptop @item.TENSP.Substring(0,30)...</strong><br /><a href="@Url.Action("XemChiTiet","LAPTOP",new {@ms=item.MASP})">Xem chi tiết</a></p>
            }
            else
            {
                <p><strong title="@item.TENSP">Laptop @item.TENSP</strong><br /><a href="@Url.Action("XemChiTiet","LAPTOP",new {@ms=item.MASP})">Xem chi tiết</a></p>
                <div class="clear"></div>
            }
        </div>
        }       
      }
</div>

DOANWEB/DOANWEB/Views/NSX/NSXPartial.cshtml
@using DOANWEB.Models;
@model List<DOANWEB.NSX>

<ul class ="list-group list-group-flush text-left">
    <li class="list-group-item" style="background-color:red;"><a href ="#" style="text-transform:uppercase; text-decoration:none; color:white; font-weight: bold">LAPTOP THEO HÃNG</a></li>
    @{
        foreach (var item in Model)
        {
            <li class="list-group-item">
                <a href="@Url.Action("LAPTOPTHEONSX","NSX", new {@maNSX = item.MANSX})" style="text-transform:uppercase; text-decoration:none; color:black;">@item.TENNSX</a>
            </li>
        }
        <li class="list-group-item"><a href="#" style="text-transform:uppercase;text-decoration:none;"></a></li>
    }
</ul>