DOANWEB/DOANWEB/Controllers/LAPTOPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEB.Controllers
{
    public class LAPTOPController : Controller
    {
        //
        // GET: /LAPTOP/
        MUABANLAPTOPDataContext db = new MUABANLAPTOPDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LAPPartial()
        {
            var ListSP = db.SANPHAMs.OrderBy(cd => cd.GIABAN).ToList();

            return View(ListSP);
        }
        public ActionResult XemChiTiet(string ms)
        {
            SANPHAM SP = db.SANPHAMs.Single(s => s.MASP == ms);
            if (SP == null)
            {
                return HttpNotFound();
            }
            return View(SP);
        }
        public ActionResult KhuyenMai()
        {
            var ListKM = db.KHUYENMAIs.OrderBy(cd => cd.MATIN).ToList();

            return View(ListKM);
        }
    }
}

DOANWEB/DOANWEB/Controllers/LOAIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANWEB.Controllers
{
    public class LOAIController : Controller
    {
        //
        // GET: /LOAI/

        MUABANLAPTOPDataContext db = new MUABANLAPTOPDataContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LOAIPartial()
        {
            var ListLOAI = db.LOAIs.Take(10).OrderBy(cd => cd.MALOAI).ToList();

            return View(ListLOAI);
        }
        public ActionResult LAPTOPTHEOLOAI(string ML)
        {
            var ListLAPTOP = db.SANPHAMs.Where(s => s.MALOAI == ML).OrderBy(s => s.GIABAN).ToList();
            if (ListLAPTOP.Count == 0)
            {
                ViewBag.LAPTOP = "Không có sách nào thuộc mục này !";
            }
            return View(ListLAPTOP);
        }
    }
}

DOANWEB/DOANWEB/Views/LOAI/LAPTOPTHEOLOAI.cshtml
@{
    ViewBag.Title = "LAPTOPTHEOLOAI";
    Layout = "~/Views/SHARE/USERLAYOUT.cshtml";
}

<h2>LAPTOP THEO NHU CẦU SỬ DỤNG</h2>
@ViewBag.LAPTOP
<div class="row">
    @{
        foreach (var item in Model)
        {
        <div class="col-4">
            <img src="@Url.Content("~/HinhAnhSP/"+item.HINHANH)" width="70%" height="70%" alt="Image" />
            @if (item.TENSP.Length > 30)
            {
                <p><strong title="@item.TENSP">Laptop @item.TENSP.Substring(0,30)...</strong><br /><a href="@Url.Action("XemChiTiet","LAPTOP",new {@ms=item.MASP})">Xem chi tiết</a></p>
            }
            else
            {
                <p><strong title="@item.TENSP">Laptop @item.TENSP</strong><br /><a href="@Url.Action("XemChiTiet","LAPTOP",new {@ms=item.MASP})">Xem chi tiết</a></p>
                <div class="clear"></div>
            }
        </div>
        }       
      }
</div>

DOANWEB/DOANWEB/Views/LOAI/LOAIPartial.cshtml
@using DOANWEB.Models;
@model List<DOANWEB.LOAI>

<ul class ="list-group list-group-flush text-left">
    <li class="list-group-item" style="background-color:red;"><a href ="#" style="text-transform:uppercase; text-decoration:none; color:white; font-weight: bold">LAPTOP THEO NHU CẦU</a></li>
    @{
        foreach (var item in Model)
        {
            <li class="list-group-item">
                <a href="@Url.Action("LAPTOPTHEOLOAI","LOAI", new {@ML = item.MALOAI})" style="text-transform:uppercase; text-decoration:none; color:black;">@item.TENLOAI</a>
            </li>
        }
        <li class="list-group-item"><a href="#" style="text-transform:uppercase;text-decoration:none;"></a></li>
    }
</ul>